/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.projetoindividual.projetoindividual;

import java.util.concurrent.ThreadLocalRandom;

/**
 *
 * @author User
 */
public class ProjetoIndividual extends javax.swing.JFrame {

    /**
     * Creates new form ProjetoIndividual
     */
    public ProjetoIndividual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bp3 = new javax.swing.JProgressBar();
        bp1 = new javax.swing.JProgressBar();
        bp2 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        butao = new javax.swing.JButton();
        medida1 = new javax.swing.JLabel();
        medida2 = new javax.swing.JLabel();
        medida3 = new javax.swing.JLabel();
        max1 = new javax.swing.JLabel();
        min1 = new javax.swing.JLabel();
        med1 = new javax.swing.JLabel();
        max2 = new javax.swing.JLabel();
        min2 = new javax.swing.JLabel();
        med2 = new javax.swing.JLabel();
        max3 = new javax.swing.JLabel();
        mi3 = new javax.swing.JLabel();
        med3 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CPU:");

        jLabel2.setText("Disco:");

        jLabel5.setText("Memória:");

        butao.setText("Fazer leitura dos dados");
        butao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoActionPerformed(evt);
            }
        });

        max1.setText("Máximo:");

        min1.setText("Mínimo:");

        med1.setText("Média:");

        max2.setText("Máximo:");

        min2.setText("Mínimo:");

        med2.setText("Média:");

        max3.setText("Máximo:");

        mi3.setText("Mínimo:");

        med3.setText("Média:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bp2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bp1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 63, Short.MAX_VALUE)
                                        .addComponent(max3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(max2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(max1, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(mi3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(med3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(min1)
                                            .addComponent(min2))
                                        .addGap(76, 76, 76)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(med2)
                                            .addComponent(med1))))
                                .addGap(49, 49, 49))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bp3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(364, 364, 364))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(butao)
                                .addGap(251, 251, 251))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(medida1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(medida2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(medida3)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(bp1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(max1)
                        .addComponent(min1)
                        .addComponent(med1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(medida1)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bp2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(max2)
                        .addComponent(min2)
                        .addComponent(med2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(medida2)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bp3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(medida3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(max3)
                                .addComponent(mi3)
                                .addComponent(med3)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50)
                .addComponent(butao)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Integer contador=0;
    
    Double acumulador1=0.0;
    Double acumulador2=0.0;
    Double acumulador3=0.0;
    
    Double maxCPU= 0.0;
    Double minCPU= 0.0;
    
    Double maxDiscos= 0.0;
    Double minDisco= 0.0;
    
    Double maxMemoria= 0.0;
    Double minMemoria= 0.0;
    
    private void butaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoActionPerformed
        
        bp1.setMaximum(1800);
        bp2.setMaximum(932);
        bp3.setMaximum(4);
        
        Integer alt1= ThreadLocalRandom.current().nextInt(0,1800);
        Integer alt2= ThreadLocalRandom.current().nextInt(0,932);
        Integer alt3= ThreadLocalRandom.current().nextInt(0,4);
        
        bp1.setValue(alt1);
        bp2.setValue(alt2);
        bp3.setValue(alt3);
        
        Double conv1= Double.valueOf(alt1);
        Double conta= (conv1/1000);
        
        
        medida1.setText(String.format("%.2f GHz", conta));
        medida2.setText(String.format("%d GB", alt2));
        medida3.setText(String.format("%d GB", alt3));
        
        bp1.setStringPainted(true);
        bp2.setStringPainted(true);
        bp3.setStringPainted(true);
        
        Double conv2= Double.valueOf(alt2);
        Double conv3= Double.valueOf(alt3);
        
        Double porcent = (conv1/1800)*100;
        Double porcent2 = (conv2/932)*100;
        Double porcent3 = (conv3/4)*100;
        
        String mostrar= String.format("%.0f", porcent);
        String mostrar2= String.format("%.0f", porcent2);
        String mostrar3= String.format("%.0f", porcent3);        
        
        bp1.setString(mostrar+"%");
        bp2.setString(mostrar2+"%");
        bp3.setString(mostrar3+"%");
        
        contador++;
        
        acumulador1= acumulador1+ conv1;
        acumulador2= acumulador2+ conv2;
        acumulador3= acumulador3+ conv3;
        
        Double media1= acumulador1/contador;
        Double media2= acumulador2/contador;
        Double media3= acumulador3/contador;
        
        String mediatexto1=String.format("%.2f", media1);
        String mediatexto2=String.format("%.2f", media2);
        String mediatexto3=String.format("%.2f", media3);
        
        med1.setText("Média:"+ mediatexto1+" GHz");
        med2.setText("Média:"+ mediatexto2+" GB");
        med3.setText("Média:"+ mediatexto3+"GB");
        
        if (maxCPU<conv1 || maxCPU==0.0) {
           maxCPU=conv1;
           String maxTextoCPU = String.format("%.2f", maxCPU);
           max1.setText("Máximo: "+maxTextoCPU+" GHz");
        }
       if (minCPU>conv1 || minCPU==0.0) {
           minCPU=conv1;
           String minTextoCPU = String.format("%.2f", minCPU);
           min1.setText("Mínimo: "+minTextoCPU+" GHz");
        }
       
       if (maxDiscos<conv2 || maxDiscos==0.0) {
           maxDiscos=conv2;
           String maxTextoDisco = String.format("%.2f", maxDiscos);
           max2.setText("Máximo: "+maxTextoDisco+" GB");
        }
       if (minDisco>conv2 || minDisco==0.0) {
           minDisco=conv2;
           String minTextoDisco = String.format("%.2f", minDisco);
           min2.setText("Mínimo: "+minTextoDisco+" GB");
        }
        if (maxMemoria<conv3 || maxMemoria==0.0) {
           maxMemoria=conv3;
           String maxTextomemoria = String.format("%.2f", maxMemoria);
           max3.setText("Máximo: "+maxTextomemoria+" GB");
        }
       if (minMemoria>conv3 || minMemoria==0.0) {
           minMemoria=conv3;
           String minTextoMemoria = String.format("%.2f", minMemoria);
           mi3.setText("Mínimo: "+minTextoMemoria+" GB");
        }
    }//GEN-LAST:event_butaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoIndividual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bp1;
    private javax.swing.JProgressBar bp2;
    private javax.swing.JProgressBar bp3;
    private javax.swing.JButton butao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel max1;
    private javax.swing.JLabel max2;
    private javax.swing.JLabel max3;
    private javax.swing.JLabel med1;
    private javax.swing.JLabel med2;
    private javax.swing.JLabel med3;
    private javax.swing.JLabel medida1;
    private javax.swing.JLabel medida2;
    private javax.swing.JLabel medida3;
    private javax.swing.JLabel mi3;
    private javax.swing.JLabel min1;
    private javax.swing.JLabel min2;
    // End of variables declaration//GEN-END:variables
}
